apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-api
  namespace: development
  labels:
    app: user-management-api
    version: "1.0.6"
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-management-api
        version: "1.0.4"
    spec:
      containers:
        - name: user-management-api
          image: user-management-api:1.0.6
          imagePullPolicy: IfNotPresent          # Use local Docker Desktop image
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0 -Djava.awt.headless=true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
      restartPolicy: Always
